export const Columns = {
    "Schools": [{
        key: "schoolName",
        title: "Schule",
        sortable: true,
        ascending: false,
        fixed: true,
        isHidden: false,
        isDropdownActive: false
    }, {
        key: "schoolKey",
        title: "Schul-Identifikation",
        sortable: true,
        ascending: false,
        fixed: true,
        isHidden: false,
        isDropdownActive: false
    }, {
        key: "partnerProjects",
        title: "Partner-Projekt(e)",
        sortable: false,
        fixed: false,
        align: "center",
        isHidden: false
    }, {
        key: "administrator",
        title: "Administrator",
        sortable: true,
        ascending: false,
        fixed: false,
        isHidden: false,
        isDropdownActive: false
    }, {
        key: "joiningDate",
        title: "Beitrittsdatum",
        sortable: true,
        ascending: false,
        fixed: false,
        isHidden: false,
        isDropdownActive: false
    }, {
        key: "classTeacher",
        title: "Klassen-Lehrer",
        sortable: false,
        fixed: false,
        align: "center",
        isHidden: false
    }, {
        key: "subjectTeacher",
        title: "Fach-Lehrer",
        sortable: false,
        fixed: false,
        align: "center",
        isHidden: false
    }, {
        key: "students",
        title: "Schüler",
        sortable: false,
        fixed: false,
        align: "center",
        isHidden: false
    }, {
        key: "subscription",
        title: "Abonnement",
        sortable: true,
        ascending: false,
        fixed: false,
        isHidden: false,
        isDropdownActive: false
    }]
}